name: Automation - Add all new issues to roadmap project

on:
  issues:
    types:
      - opened

jobs:
  add-label:
    name: Add label to issue
    runs-on: ubuntu-latest
    steps:
      - name: Add label to new issue
        uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          default-labels: '["App", "help wanted"]'

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Shuffle/projects/8
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
